stages:
  - build

default:
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/

# Build stage
build-js:
  stage: build
  image:
    name: node:12
  artifacts:
    paths:
      - static
  script:
    - npm install --cache .npm --prefer-offline
    - npm run build
